### ISSUE TITLE
Remove IDENTITY support from Celesta 7

### ISSUE THREAD

**Issue by inponomarev** [CourseOrchestra/celesta#104]
Time has come to remove undocumented and deprecated support of `IDENTITY` keyword from Celesta 7,
together with clumsy sequences imitation for older versions of MS SQL (table `sequences` in `celesta.sql` and auto-generated SequencesCursor, and everything that uses them).

This involves re-writing of tests that use `IDENTITY` keyword for `CREATE SEQUENCE`-`DEFAULT NEXTVAL` as described [here](https://corchestra.ru/wiki/index.php?title=%D0%AF%D0%B7%D1%8B%D0%BA_Celesta-SQL#.D0.9E.D0.BF.D1.80.D0.B5.D0.B4.D0.B5.D0.BB.D0.B5.D0.BD.D0.B8.D1.8F_.D0.BF.D0.BE.D0.BB.D0.B5.D0.B9).

**Comment by packpaul** [comment]
PR: https://github.com/CourseOrchestra/celesta/pull/109
