### ISSUE TITLE
Implement WITH NO AUTOUPDATE for CREATE GRAIN in CelestaSQL

### ISSUE THREAD

**Issue by inponomarev** [CourseOrchestra/celesta#107]
We now have [`WITH NO AUTOUPDATE`](https://corchestra.ru/wiki/index.php?title=%D0%AF%D0%B7%D1%8B%D0%BA_Celesta-SQL#.D0.9E.D0.BF.D1.86.D0.B8.D0.B8) postfix for `CREATE TABLE` clause. This forces Celesta to skip table structure update during initialization.

We also need `[WITH [NO] AUTOUPDATE]` postfix for `CREATE GRAIN` clause. `NO AUTOUPDATE`, if set, should override the setting from `celesta.grains` table and always skip the grain update. `WITH AUTOUPDATE` should be simply ignored (should work as it works now with no postfix).

Implementation of this issue should involve an automated test on H2 database with the following outline: 

1) initialize Celesta with H2 / scoreV1 and grains A, B, C 
2) set `lock` status (4) for grain A in celesta.grains
3) do not shut down H2, re-initialize Celesta with H2 / scoreV2 with modified grains A, B, C; grain A `with autoupdate`, grain B `with no autoupdate`.
4) verify that grain A and B are not updated, grain C is updated. 

CelestaSQL documentation should also be updated.

**Comment by packpaul** [comment]
PR: https://github.com/CourseOrchestra/celesta/pull/110
